### ISSUE TITLE
Feature Request: welcome

### ISSUE THREAD

**Issue by anupammaurya6767** [anupammaurya6767/luffy#49]
*Description:
Set a welcome message for the group.

Extended Description:*
```Set a welcome message for the group.```

**Comment by Tomkndn** [comment]
Hey,It looks interesting.can i try to implement this feature.
Bit confused is this a feature to greet a new person joining the group?

**Comment by anupammaurya6767** [comment]
@Tomkndn yes to greet a new person joining the group
and the welcome msg can be different for different groups and admin can change the welcome msg for a particular group

**Comment by Tomkndn** [comment]
Please specify more details about the env variables.

**Comment by anupammaurya6767** [comment]
> Please specify more details about the env variables.

authcollectionName=auth_info
folderID=your-folder-id
ALLOWED_ID=your-allowed-id
LEECH_LIMIT=your-leech-limit # in bytes
----------------------------------------------------------------
ALLOWED_ID = "ANY STRING"
LEECH LIMIT = "maximum torrent size" (in bytes)
folderID = "drive folder id where to upload files and folders"
Keep authcollectionName as it is

**Comment by Tomkndn** [comment]
PLease assign me this task as I will make a PR request on this issue.

**Comment by Tomkndn** [comment]
Thanks again.

**Comment by Tomkndn** [comment]
Hey, please label it properly.
