### ISSUE TITLE
Enhancement : Improving Readme.md

### ISSUE THREAD

**Issue by devlohani99** [anupammaurya6767/luffy#57]
**Is your feature request related to a problem? Please describe.**
The main aim of readme file is to make new users to get the idea about the project and its uses

**Describe the solution you'd like**
![Screenshot 2024-05-12 155918](https://github.com/anupammaurya6767/luffy/assets/142163543/cda03f83-dc76-4871-b913-bbaeb7030d17)

**Describe alternatives you've considered**

->Add Git commands
->Deployment
->Tech stack used

**Comment by devlohani99** [comment]
@anupammaurya6767  I want to design the readme file for the same , kindly assign me under GSSOC24

**Comment by anupammaurya6767** [comment]
@devlohani99 check issue #9
