### ISSUE TITLE
Update Readme.md documentation

### ISSUE THREAD

**Issue by SuhainaFathimaM** [anupammaurya6767/luffy#61]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SuhainaFathimaM** [comment]
Assign this issue as GSSoC'24 .. 
I would like to work on this issue..
@anupammaurya6767  Please assign me this issue

**Comment by anupammaurya6767** [comment]
@SuhainaFathimaM check issue #9
