### ISSUE TITLE
Enchance Readme.md

### ISSUE THREAD

**Issue by Santhosh-Siddhardha** [anupammaurya6767/luffy#62]
**Is your feature request related to a problem? Please describe.**
The current README.md file lacks detailed information and could be enhanced to provide better guidance and understanding for users and developers.

**Describe the solution you'd like**
I would like to enhance the README.md file by adding comprehensive sections that cover project overview, contribution guidelines, and other relevant details. This will improve user experience and facilitate smoother onboarding for new contributors.

**Describe alternatives you've considered**
An alternative would be to create separate documentation files or a wiki, but integrating these details directly into the README.md file will make it more accessible and visible to users visiting the project repository.

**Additional context**
Screenshots illustrating the changes will be included in PR to visually demonstrate the improvements to the README.md file layout and content structure.

**Comment by anupammaurya6767** [comment]
@Santhosh-Siddhardha check issue #9
