### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by suhanipaliwal** [anupammaurya6767/luffy#65]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by anupammaurya6767** [comment]
@suhanipaliwal work on existing issues first or create an issue regarding new feature or to fix existing one
