### ISSUE TITLE
add the dockerignore

### ISSUE THREAD

**Issue by agarwalhimanshugaya** [anupammaurya6767/luffy#77]
**Is your feature request related to a problem? Please describe.**
when i run your project with the help of docker then it take many space because you copy all the things in docker but we have to add dockerignore so that some file donot copy

**Describe the solution you'd like**
Add dockerignore file so that nodemodules and bigfiles ignored

**Describe alternatives you've considered**

**Additional context**

**Comment by ankita685** [comment]
pls assigm me this under gssoc24

**Comment by anupammaurya6767** [comment]
@ankita685 go ahead

**Comment by agarwalhimanshugaya** [comment]
@anupammaurya6767 i open the issue you assign to other person
