### ISSUE TITLE
Write a Readme for the project

### ISSUE THREAD

**Issue by anupammaurya6767** [anupammaurya6767/luffy#9]
Is your feature request related to a problem? Please describe.
The project currently lacks a comprehensive Readme file, which is essential for new contributors to understand the project and how to set it up locally.

Describe the solution you'd like
Create a Readme.md file that provides an overview of the project, including its purpose, features, setup instructions, configuration, and usage guidelines.

Describe alternatives you've considered
An alternative could be creating separate documents for specific sections of the Readme, but a single comprehensive Readme.md file would be more user-friendly.

Additional context
Adding a Readme.md file will improve the project's documentation and make it easier for contributors to get started with the project.

**Comment by yashisrani** [comment]
@anupammaurya6767 kindly assign me this issue under #gssoc'24 .. I will Enhance Readme file and make it beautiful , clear and usable for other folks ..

**Comment by IP80808080** [comment]
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me?  Thank you! 🚀

**Comment by harini-1597** [comment]
Hi. Noticed this issue is still not resolved as the README is still just two lines. Could you assign it to me? I'll have it done asap

**Comment by anupammaurya6767** [comment]
@harini-1597 go ahead

**Comment by harini-1597** [comment]
How does this look?

https://github.com/anupammaurya6767/luffy/assets/128628820/b7f9f61a-6db7-4a8c-8e21-cc5e4911812d

**Comment by anupammaurya6767** [comment]
@harini-1597 nice create  a pull request
